In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices_2.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [7]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

#### Formula    Price = (m1 * area) + (m2 * bedrooms) + (m3 * age) + b

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [11]:
reg.intercept_

383724.9999999998

In [12]:
reg.predict([[3000, 3, 40]])

array([444400.])

In [13]:
137.25*3000 + -26025.*3 + -6825.*40 + 383724.9999999998

444399.9999999998

In [15]:
reg.predict([[2500, 4, 5]])

array([588625.])