In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

from sklearn.datasets import load_digits

digits = load_digits()

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [29]:
lr = LogisticRegression(solver='liblinear', multi_class='auto')

lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9115191986644408

In [20]:
svm = SVC(gamma='scale')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [10]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

In [11]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [49]:
get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test)

0.9115191986644408

In [18]:
get_score(SVC(gamma='scale'), X_train, X_test, y_train, y_test)

0.9888888888888889

In [47]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='scale'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [48]:
print('lr: ', scores_lr)
print('sv: ', scores_svm)
print('rf: ', scores_rf)

lr:  [0.8964941569282137, 0.9515859766277128, 0.9115191986644408]
sv:  [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
rf:  [0.9248747913188647, 0.9499165275459098, 0.9215358931552587]


In [33]:
from sklearn.model_selection import cross_val_score

In [37]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='auto'), digits.data, digits.target, cv=3)

array([0.89534884, 0.94991653, 0.90939597])

In [38]:
cross_val_score(SVC(gamma='scale'), digits.data, digits.target, cv=3)

array([0.96677741, 0.97996661, 0.9647651 ])

In [39]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93023256, 0.95158598, 0.9261745 ])